#!/usr/bin/env python3
"""Regenerate the toolset-selection context-savings report.

Measures the concrete tool-schema byte/token cost of the full worker ceiling vs
the narrowed selection for each task in the shared corpus
(``tests/hermes_cli/toolset_corpus.py``) and writes the Markdown report at
``docs/reports/toolset-selection-savings.md``.

    python scripts/measure_toolset_savings.py            # write the report
    python scripts/measure_toolset_savings.py --check    # print, don't write

The same corpus backs ``tests/hermes_cli/test_toolset_savings.py``, so the report
and the asserted thresholds stay in lock-step. Numbers depend on the live tool
registry (tool descriptions/params), so re-run after changing any tool schema.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tests.hermes_cli import toolset_corpus as corpus  # noqa: E402

REPORT_PATH = REPO_ROOT / "docs" / "reports" / "toolset-selection-savings.md"

_KIND_LABEL = {
    "positive": "relevant",
    "minimal": "minimal",
    "denylist": "denylist",
    "worst_case": "worst-case",
}


def _rows_table(rep: corpus.Report) -> str:
    header = (
        "| case | kind | selected (non-base) | tools tok | worker tok | saved % |\n"
        "| --- | --- | --- | ---: | ---: | ---: |"
    )
    lines = [header]
    for r in rep.rows:
        sel = ", ".join(r.non_base) if r.non_base else "_(base only)_"
        lines.append(
            f"| {r.case.name} | {_KIND_LABEL.get(r.case.kind, r.case.kind)} | "
            f"{sel} | {r.tokens} | {r.worker_tokens} | {r.saved_pct} |"
        )
    return "\n".join(lines)


def render(rep: corpus.Report) -> str:
    base_saved = round(100 * (rep.ceiling_tokens - rep.base_tokens) / rep.ceiling_tokens, 1)
    ceiling_bytes = rep.ceiling_tokens * corpus.CHARS_PER_TOKEN
    return f"""# Toolset selection — context savings report

_Auto-generated by `scripts/measure_toolset_savings.py` from the corpus in
`tests/hermes_cli/toolset_corpus.py`. Do not hand-edit; re-run the script.
Token estimates use the runtime's `chars/4` estimator
(`tools.tool_search.estimate_tokens_from_schemas`)._

## What is measured

Each task is run through the deterministic selector (`mode: narrow`) against a
broad "elias-class" worker ceiling of {len(corpus.FULL_CEILING)} toolsets. The
resulting toolset set is resolved to its concrete tool JSON schemas via the live
tool registry, serialized compactly, and sized in bytes and estimated tokens.
"Before" is the full ceiling; "after" is the narrowed selection.

Two figures are reported per task:

- **tools tok** — the narrowable schema cost (the part the selector controls).
- **worker tok** — end-to-end, including the {rep.kanban_tokens}-token `kanban`
  lifecycle floor that `model_tools` appends to every worker regardless of
  `--toolsets`. This is the honest number to compare against the ~17k-token
  worker surface.

## Baseline (full worker ceiling)

| surface | tools | bytes | est. tokens |
| --- | ---: | ---: | ---: |
| base only (`{", ".join(corpus.BASE)}`) | — | {rep.base_tokens * corpus.CHARS_PER_TOKEN} | {rep.base_tokens} |
| full narrowable ceiling ({len(corpus.FULL_CEILING)} toolsets) | {rep.ceiling_tools} | {ceiling_bytes} | {rep.ceiling_tokens} |
| kanban lifecycle floor (always appended) | — | {rep.kanban_tokens * corpus.CHARS_PER_TOKEN} | {rep.kanban_tokens} |
| **full worker surface (ceiling + kanban)** | — | {rep.worker_full_tokens * corpus.CHARS_PER_TOKEN} | **{rep.worker_full_tokens}** |

The full worker surface is **~{rep.worker_full_tokens} tokens**, matching the
"~17k tokens" the task set out to cut. A base-only worker drops the narrowable
schema by **{base_saved}%**.

## Per-task savings

{_rows_table(rep)}

## Headline savings (vs full narrowable ceiling)

| scenario | saved % |
| --- | ---: |
| typical (median of non-worst tasks) | **{rep.typical_saved_pct}%** |
| mean across the corpus | {rep.mean_saved_pct}% |
| worst case (task touching almost everything) | {rep.worst_saved_pct}% |

Typical narrow tasks shed roughly **{rep.typical_saved_pct}%** of the toolset
schema (~{int(rep.ceiling_tokens * rep.typical_saved_pct / 100)} tokens saved of
{rep.ceiling_tokens}). Because the {rep.kanban_tokens}-token kanban floor is
constant, the end-to-end worker-surface saving is lower but still large (see the
`worker tok` column: a base-only worker is ~{rep.base_tokens + rep.kanban_tokens} tokens vs ~{rep.worker_full_tokens}).

## Known limitations

- **Estimator, not tokenizer.** Sizes use `chars/4`, the same order-of-magnitude
  estimator the runtime uses to gate tool-search. Real per-model tokenization
  differs by ±10-20%; the *relative* before/after ratio is stable, the absolute
  token counts are approximate.
- **Ceiling is representative, not universal.** Savings scale with how broad the
  assignee profile's ceiling is. A profile that already ships a narrow
  `platform_toolsets.cli` saves proportionally less; a very broad one saves more.
- **Keyword ambiguity can over-select.** Some stems live in more than one table —
  e.g. `screenshot` is a keyword for both `browser` and `vision`, so a
  screenshot-analysis task earns `browser` too (see the `vision` row). This is
  safe under the fail-open design (over-selecting only forgoes savings, never
  removes a needed tool) but it dilutes the win on such tasks. Tunable from real
  selection logs without code changes (the rule tables are data).
- **Worst case saves little by design.** A task that genuinely needs almost every
  capability narrows to almost the full ceiling ({rep.worst_saved_pct}% here).
  Narrowing helps the common, focused task; it cannot help a task that truly
  needs everything.
- **Kanban floor is not narrowable.** The {rep.kanban_tokens}-token lifecycle
  surface is required for a worker to complete/block/heartbeat and is out of
  scope for this selector.
- **Shipped dark.** `mode` defaults to `off` (full ceiling, today's behaviour);
  these savings are realized only when a profile/board opts into `mode: narrow`.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="print the report to stdout instead of writing the file")
    args = ap.parse_args()

    rep = corpus.measure()
    text = render(rep)
    if args.check:
        sys.stdout.write(text)
        return 0
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {REPORT_PATH.relative_to(REPO_ROOT)} "
          f"(typical {rep.typical_saved_pct}%, worst {rep.worst_saved_pct}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
